default_context:
  project_name: 'Vexel'
  project_slug: 'vexel'
  domain_main: 'vexel.vn'
  domain_staging: 'staging.vexel.vn'
  domain_base_api_url: 'http://vexel.vn/api/v1'
  domain_base_ws_url: 'ws://vexel.vn/api/v1'
  docker_swarm_stack_name_main: 'vexel-vn'
  docker_swarm_stack_name_staging: 'staging-vexel-vn'
  secret_key: 'changethis'
  first_superuser: 'admin@vexel.vn'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.vexel.vn", "https://staging.vexel.vn", "https://vexel.vn"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@vexel.vn'
  smtp_emails_from_name: 'Justin'
  smtp_emails_to_email: 'info@vexel.vn'
  mongodb_uri: 'mongodb'
  mongodb_database: 'app'
  traefik_constraint_tag: 'vexel.vn'
  traefik_constraint_tag_staging: 'staging.vexel.vn'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
