import {
  IUserProfile,
  IUserProfileUpdate,
  IUserProfileCreate,
  IUserOpenProfileCreate,
} from "./profile";

import {
  ITokenResponse,
  IWebToken,
  INewTOTP,
  IEnableTOTP,
  ISendEmail,
  IMsg,
  INotification,
  IErrorResponse,
} from "./utilities";

// Agent Management interfaces
import {
  AgentType,
  AgentStatus,
  IKnowledgeSource,
  IToolConfiguration,
  IAgentConfiguration,
  IAgentConfigurationCreate,
  IAgentConfigurationUpdate,
  IAgentSession,
  IAgentSessionCreate,
  IAgentSessionUpdate,
  IAgentMetrics,
  IAgentChatRequest,
  IAgentChatResponse,
  IAgentListResponse,
  IAgentSearchRequest,
} from "./agent";

// Chat Management interfaces
import {
  MessageRole,
  MessageType,
  ConversationStatus,
  IMessageContent,
  IToolCall,
  IChatConversation,
  IChatConversationCreate,
  IChatConversationUpdate,
  IMessage,
  IMessageCreate,
  IMessageUpdate,
  IConversationFeedback,
  IConversationFeedbackCreate,
  IConversationTemplate,
  IConversationTemplateCreate,
  IConversationTemplateUpdate,
  IChatRequest,
  IChatResponse,
  IConversationListResponse,
  IMessageListResponse,
  IConversationSearchRequest,
} from "./chat";

// Workflow Management interfaces
import {
  WorkflowStatus,
  StepType,
  IWorkflowStepConfig,
  IWorkflowTemplate,
  IWorkflowTemplateCreate,
  IWorkflowTemplateUpdate,
  IWorkflowExecution,
  IWorkflowExecutionCreate,
  IWorkflowExecutionUpdate,
  IWorkflowStepExecution,
  IWorkflowSchedule,
  IWorkflowScheduleCreate,
  IWorkflowScheduleUpdate,
  IWorkflowExecuteRequest,
  IWorkflowExecuteResponse,
  IWorkflowListResponse,
  IWorkflowExecutionListResponse,
  IWorkflowSearchRequest,
} from "./workflow";

// Knowledge Management interfaces
import {
  KnowledgeUploadMethod,
  KnowledgeCategory,
  KnowledgeFileType,
  KnowledgeStatus,
  CollectionType,
  WorkspaceType,
  IKnowledgeItem,
  IKnowledgeUploadRequest,
  IKnowledgeUploadResponse,
  IKnowledgeTextUploadRequest,
  IKnowledgeUrlUploadRequest,
  IKnowledgeSearchRequest,
  IKnowledgeSearchResponse,
  IKnowledgeListResponse,
  IKnowledgeDeleteRequest,
  IKnowledgeDeleteResponse,
  IKnowledgeUploadProgress,
  IKnowledgeState,
  IKnowledgeFormData,
  IKnowledgeValidationError,
  IKnowledgeUploadOptions,
  IKnowledgeAnalytics,
  IKnowledgeCollectionInfo,
  IKnowledgeBulkDeleteRequest,
  IKnowledgeBulkDeleteResponse,
  IKnowledgeExportRequest,
  IKnowledgeExportResponse,
  // Collections and Workspace interfaces
  ICollectionPermissions,
  IKnowledgeCollection,
  ICollectionCreateRequest,
  ICollectionUpdateRequest,
  ICollectionDetailsResponse,
  IWorkspaceMember,
  IWorkspaceSettings,
  IWorkspace,
  IWorkspaceCreateRequest,
  IWorkspaceUpdateRequest,
  IFileMoveRequest,
  IBulkFileMoveRequest,
} from "./knowledge";

// https://stackoverflow.com/a/64782482/295606
interface IKeyable {
  [key: string]: any | any[];
}

// Export enums directly (not as types)
export {
  AgentType,
  AgentStatus,
  MessageRole,
  MessageType,
  ConversationStatus,
  WorkflowStatus,
  StepType,
  KnowledgeUploadMethod,
  KnowledgeCategory,
  KnowledgeFileType,
  KnowledgeStatus,
  CollectionType,
  WorkspaceType,
};

// Export types
export type {
  IKeyable,
  IUserProfile,
  IUserProfileUpdate,
  IUserProfileCreate,
  IUserOpenProfileCreate,
  ITokenResponse,
  IWebToken,
  INewTOTP,
  IEnableTOTP,
  ISendEmail,
  IMsg,
  INotification,
  IErrorResponse,
  // Agent Management types
  IKnowledgeSource,
  IToolConfiguration,
  IAgentConfiguration,
  IAgentConfigurationCreate,
  IAgentConfigurationUpdate,
  IAgentSession,
  IAgentSessionCreate,
  IAgentSessionUpdate,
  IAgentMetrics,
  IAgentChatRequest,
  IAgentChatResponse,
  IAgentListResponse,
  IAgentSearchRequest,
  // Chat Management types
  IMessageContent,
  IToolCall,
  IChatConversation,
  IChatConversationCreate,
  IChatConversationUpdate,
  IMessage,
  IMessageCreate,
  IMessageUpdate,
  IConversationFeedback,
  IConversationFeedbackCreate,
  IConversationTemplate,
  IConversationTemplateCreate,
  IConversationTemplateUpdate,
  IChatRequest,
  IChatResponse,
  IConversationListResponse,
  IMessageListResponse,
  IConversationSearchRequest,
  // Workflow Management types
  IWorkflowStepConfig,
  IWorkflowTemplate,
  IWorkflowTemplateCreate,
  IWorkflowTemplateUpdate,
  IWorkflowExecution,
  IWorkflowExecutionCreate,
  IWorkflowExecutionUpdate,
  IWorkflowStepExecution,
  IWorkflowSchedule,
  IWorkflowScheduleCreate,
  IWorkflowScheduleUpdate,
  IWorkflowExecuteRequest,
  IWorkflowExecuteResponse,
  IWorkflowListResponse,
  IWorkflowExecutionListResponse,
  IWorkflowSearchRequest,
  // Knowledge Management types
  IKnowledgeItem,
  IKnowledgeUploadRequest,
  IKnowledgeUploadResponse,
  IKnowledgeTextUploadRequest,
  IKnowledgeUrlUploadRequest,
  IKnowledgeSearchRequest,
  IKnowledgeSearchResponse,
  IKnowledgeListResponse,
  IKnowledgeDeleteRequest,
  IKnowledgeDeleteResponse,
  IKnowledgeUploadProgress,
  IKnowledgeState,
  IKnowledgeFormData,
  IKnowledgeValidationError,
  IKnowledgeUploadOptions,
  IKnowledgeAnalytics,
  IKnowledgeCollectionInfo,
  IKnowledgeBulkDeleteRequest,
  IKnowledgeBulkDeleteResponse,
  IKnowledgeExportRequest,
  IKnowledgeExportResponse,
  // Collections and Workspace types
  ICollectionPermissions,
  IKnowledgeCollection,
  ICollectionCreateRequest,
  ICollectionUpdateRequest,
  ICollectionDetailsResponse,
  IWorkspaceMember,
  IWorkspaceSettings,
  IWorkspace,
  IWorkspaceCreateRequest,
  IWorkspaceUpdateRequest,
  IFileMoveRequest,
  IBulkFileMoveRequest,
};
